# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/184/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/184/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matheus/UP/IA/trabalhos/IA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matheus/UP/IA/trabalhos/IA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/184/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/184/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matheus/UP/IA/trabalhos/IA/CMakeFiles /home/matheus/UP/IA/trabalhos/IA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matheus/UP/IA/trabalhos/IA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IA

# Build rule for target.
IA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IA
.PHONY : IA

# fast build rule for target.
IA/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/build
.PHONY : IA/fast

DataStructures/BFSBoard.o: DataStructures/BFSBoard.c.o
.PHONY : DataStructures/BFSBoard.o

# target to build an object file
DataStructures/BFSBoard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BFSBoard.c.o
.PHONY : DataStructures/BFSBoard.c.o

DataStructures/BFSBoard.i: DataStructures/BFSBoard.c.i
.PHONY : DataStructures/BFSBoard.i

# target to preprocess a source file
DataStructures/BFSBoard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BFSBoard.c.i
.PHONY : DataStructures/BFSBoard.c.i

DataStructures/BFSBoard.s: DataStructures/BFSBoard.c.s
.PHONY : DataStructures/BFSBoard.s

# target to generate assembly for a file
DataStructures/BFSBoard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BFSBoard.c.s
.PHONY : DataStructures/BFSBoard.c.s

DataStructures/BoardList.o: DataStructures/BoardList.c.o
.PHONY : DataStructures/BoardList.o

# target to build an object file
DataStructures/BoardList.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BoardList.c.o
.PHONY : DataStructures/BoardList.c.o

DataStructures/BoardList.i: DataStructures/BoardList.c.i
.PHONY : DataStructures/BoardList.i

# target to preprocess a source file
DataStructures/BoardList.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BoardList.c.i
.PHONY : DataStructures/BoardList.c.i

DataStructures/BoardList.s: DataStructures/BoardList.c.s
.PHONY : DataStructures/BoardList.s

# target to generate assembly for a file
DataStructures/BoardList.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BoardList.c.s
.PHONY : DataStructures/BoardList.c.s

DataStructures/BoardStack.o: DataStructures/BoardStack.c.o
.PHONY : DataStructures/BoardStack.o

# target to build an object file
DataStructures/BoardStack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BoardStack.c.o
.PHONY : DataStructures/BoardStack.c.o

DataStructures/BoardStack.i: DataStructures/BoardStack.c.i
.PHONY : DataStructures/BoardStack.i

# target to preprocess a source file
DataStructures/BoardStack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BoardStack.c.i
.PHONY : DataStructures/BoardStack.c.i

DataStructures/BoardStack.s: DataStructures/BoardStack.c.s
.PHONY : DataStructures/BoardStack.s

# target to generate assembly for a file
DataStructures/BoardStack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/BoardStack.c.s
.PHONY : DataStructures/BoardStack.c.s

DataStructures/DFSBoard.o: DataStructures/DFSBoard.c.o
.PHONY : DataStructures/DFSBoard.o

# target to build an object file
DataStructures/DFSBoard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/DFSBoard.c.o
.PHONY : DataStructures/DFSBoard.c.o

DataStructures/DFSBoard.i: DataStructures/DFSBoard.c.i
.PHONY : DataStructures/DFSBoard.i

# target to preprocess a source file
DataStructures/DFSBoard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/DFSBoard.c.i
.PHONY : DataStructures/DFSBoard.c.i

DataStructures/DFSBoard.s: DataStructures/DFSBoard.c.s
.PHONY : DataStructures/DFSBoard.s

# target to generate assembly for a file
DataStructures/DFSBoard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/DFSBoard.c.s
.PHONY : DataStructures/DFSBoard.c.s

DataStructures/DFSBoardStack.o: DataStructures/DFSBoardStack.c.o
.PHONY : DataStructures/DFSBoardStack.o

# target to build an object file
DataStructures/DFSBoardStack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/DFSBoardStack.c.o
.PHONY : DataStructures/DFSBoardStack.c.o

DataStructures/DFSBoardStack.i: DataStructures/DFSBoardStack.c.i
.PHONY : DataStructures/DFSBoardStack.i

# target to preprocess a source file
DataStructures/DFSBoardStack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/DFSBoardStack.c.i
.PHONY : DataStructures/DFSBoardStack.c.i

DataStructures/DFSBoardStack.s: DataStructures/DFSBoardStack.c.s
.PHONY : DataStructures/DFSBoardStack.s

# target to generate assembly for a file
DataStructures/DFSBoardStack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/DFSBoardStack.c.s
.PHONY : DataStructures/DFSBoardStack.c.s

DataStructures/HashStack.o: DataStructures/HashStack.c.o
.PHONY : DataStructures/HashStack.o

# target to build an object file
DataStructures/HashStack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/HashStack.c.o
.PHONY : DataStructures/HashStack.c.o

DataStructures/HashStack.i: DataStructures/HashStack.c.i
.PHONY : DataStructures/HashStack.i

# target to preprocess a source file
DataStructures/HashStack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/HashStack.c.i
.PHONY : DataStructures/HashStack.c.i

DataStructures/HashStack.s: DataStructures/HashStack.c.s
.PHONY : DataStructures/HashStack.s

# target to generate assembly for a file
DataStructures/HashStack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/HashStack.c.s
.PHONY : DataStructures/HashStack.c.s

DataStructures/Heap.o: DataStructures/Heap.c.o
.PHONY : DataStructures/Heap.o

# target to build an object file
DataStructures/Heap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Heap.c.o
.PHONY : DataStructures/Heap.c.o

DataStructures/Heap.i: DataStructures/Heap.c.i
.PHONY : DataStructures/Heap.i

# target to preprocess a source file
DataStructures/Heap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Heap.c.i
.PHONY : DataStructures/Heap.c.i

DataStructures/Heap.s: DataStructures/Heap.c.s
.PHONY : DataStructures/Heap.s

# target to generate assembly for a file
DataStructures/Heap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Heap.c.s
.PHONY : DataStructures/Heap.c.s

DataStructures/IDSBoard.o: DataStructures/IDSBoard.c.o
.PHONY : DataStructures/IDSBoard.o

# target to build an object file
DataStructures/IDSBoard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/IDSBoard.c.o
.PHONY : DataStructures/IDSBoard.c.o

DataStructures/IDSBoard.i: DataStructures/IDSBoard.c.i
.PHONY : DataStructures/IDSBoard.i

# target to preprocess a source file
DataStructures/IDSBoard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/IDSBoard.c.i
.PHONY : DataStructures/IDSBoard.c.i

DataStructures/IDSBoard.s: DataStructures/IDSBoard.c.s
.PHONY : DataStructures/IDSBoard.s

# target to generate assembly for a file
DataStructures/IDSBoard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/IDSBoard.c.s
.PHONY : DataStructures/IDSBoard.c.s

DataStructures/MovementStack.o: DataStructures/MovementStack.c.o
.PHONY : DataStructures/MovementStack.o

# target to build an object file
DataStructures/MovementStack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/MovementStack.c.o
.PHONY : DataStructures/MovementStack.c.o

DataStructures/MovementStack.i: DataStructures/MovementStack.c.i
.PHONY : DataStructures/MovementStack.i

# target to preprocess a source file
DataStructures/MovementStack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/MovementStack.c.i
.PHONY : DataStructures/MovementStack.c.i

DataStructures/MovementStack.s: DataStructures/MovementStack.c.s
.PHONY : DataStructures/MovementStack.s

# target to generate assembly for a file
DataStructures/MovementStack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/MovementStack.c.s
.PHONY : DataStructures/MovementStack.c.s

DataStructures/Queue.o: DataStructures/Queue.c.o
.PHONY : DataStructures/Queue.o

# target to build an object file
DataStructures/Queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Queue.c.o
.PHONY : DataStructures/Queue.c.o

DataStructures/Queue.i: DataStructures/Queue.c.i
.PHONY : DataStructures/Queue.i

# target to preprocess a source file
DataStructures/Queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Queue.c.i
.PHONY : DataStructures/Queue.c.i

DataStructures/Queue.s: DataStructures/Queue.c.s
.PHONY : DataStructures/Queue.s

# target to generate assembly for a file
DataStructures/Queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Queue.c.s
.PHONY : DataStructures/Queue.c.s

DataStructures/Stack.o: DataStructures/Stack.c.o
.PHONY : DataStructures/Stack.o

# target to build an object file
DataStructures/Stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Stack.c.o
.PHONY : DataStructures/Stack.c.o

DataStructures/Stack.i: DataStructures/Stack.c.i
.PHONY : DataStructures/Stack.i

# target to preprocess a source file
DataStructures/Stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Stack.c.i
.PHONY : DataStructures/Stack.c.i

DataStructures/Stack.s: DataStructures/Stack.c.s
.PHONY : DataStructures/Stack.s

# target to generate assembly for a file
DataStructures/Stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/DataStructures/Stack.c.s
.PHONY : DataStructures/Stack.c.s

SearchAlgs/A*.o: SearchAlgs/A*.c.o
.PHONY : SearchAlgs/A*.o

# target to build an object file
SearchAlgs/A*.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make "CMakeFiles/IA.dir/SearchAlgs/A*.c.o"
.PHONY : SearchAlgs/A*.c.o

SearchAlgs/A*.i: SearchAlgs/A*.c.i
.PHONY : SearchAlgs/A*.i

# target to preprocess a source file
SearchAlgs/A*.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make "CMakeFiles/IA.dir/SearchAlgs/A*.c.i"
.PHONY : SearchAlgs/A*.c.i

SearchAlgs/A*.s: SearchAlgs/A*.c.s
.PHONY : SearchAlgs/A*.s

# target to generate assembly for a file
SearchAlgs/A*.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make "CMakeFiles/IA.dir/SearchAlgs/A*.c.s"
.PHONY : SearchAlgs/A*.c.s

SearchAlgs/BFS.o: SearchAlgs/BFS.c.o
.PHONY : SearchAlgs/BFS.o

# target to build an object file
SearchAlgs/BFS.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/BFS.c.o
.PHONY : SearchAlgs/BFS.c.o

SearchAlgs/BFS.i: SearchAlgs/BFS.c.i
.PHONY : SearchAlgs/BFS.i

# target to preprocess a source file
SearchAlgs/BFS.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/BFS.c.i
.PHONY : SearchAlgs/BFS.c.i

SearchAlgs/BFS.s: SearchAlgs/BFS.c.s
.PHONY : SearchAlgs/BFS.s

# target to generate assembly for a file
SearchAlgs/BFS.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/BFS.c.s
.PHONY : SearchAlgs/BFS.c.s

SearchAlgs/BP.o: SearchAlgs/BP.c.o
.PHONY : SearchAlgs/BP.o

# target to build an object file
SearchAlgs/BP.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/BP.c.o
.PHONY : SearchAlgs/BP.c.o

SearchAlgs/BP.i: SearchAlgs/BP.c.i
.PHONY : SearchAlgs/BP.i

# target to preprocess a source file
SearchAlgs/BP.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/BP.c.i
.PHONY : SearchAlgs/BP.c.i

SearchAlgs/BP.s: SearchAlgs/BP.c.s
.PHONY : SearchAlgs/BP.s

# target to generate assembly for a file
SearchAlgs/BP.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/BP.c.s
.PHONY : SearchAlgs/BP.c.s

SearchAlgs/DFS.o: SearchAlgs/DFS.c.o
.PHONY : SearchAlgs/DFS.o

# target to build an object file
SearchAlgs/DFS.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/DFS.c.o
.PHONY : SearchAlgs/DFS.c.o

SearchAlgs/DFS.i: SearchAlgs/DFS.c.i
.PHONY : SearchAlgs/DFS.i

# target to preprocess a source file
SearchAlgs/DFS.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/DFS.c.i
.PHONY : SearchAlgs/DFS.c.i

SearchAlgs/DFS.s: SearchAlgs/DFS.c.s
.PHONY : SearchAlgs/DFS.s

# target to generate assembly for a file
SearchAlgs/DFS.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/DFS.c.s
.PHONY : SearchAlgs/DFS.c.s

SearchAlgs/Guloso.o: SearchAlgs/Guloso.c.o
.PHONY : SearchAlgs/Guloso.o

# target to build an object file
SearchAlgs/Guloso.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Guloso.c.o
.PHONY : SearchAlgs/Guloso.c.o

SearchAlgs/Guloso.i: SearchAlgs/Guloso.c.i
.PHONY : SearchAlgs/Guloso.i

# target to preprocess a source file
SearchAlgs/Guloso.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Guloso.c.i
.PHONY : SearchAlgs/Guloso.c.i

SearchAlgs/Guloso.s: SearchAlgs/Guloso.c.s
.PHONY : SearchAlgs/Guloso.s

# target to generate assembly for a file
SearchAlgs/Guloso.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Guloso.c.s
.PHONY : SearchAlgs/Guloso.c.s

SearchAlgs/Heur.o: SearchAlgs/Heur.c.o
.PHONY : SearchAlgs/Heur.o

# target to build an object file
SearchAlgs/Heur.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Heur.c.o
.PHONY : SearchAlgs/Heur.c.o

SearchAlgs/Heur.i: SearchAlgs/Heur.c.i
.PHONY : SearchAlgs/Heur.i

# target to preprocess a source file
SearchAlgs/Heur.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Heur.c.i
.PHONY : SearchAlgs/Heur.c.i

SearchAlgs/Heur.s: SearchAlgs/Heur.c.s
.PHONY : SearchAlgs/Heur.s

# target to generate assembly for a file
SearchAlgs/Heur.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Heur.c.s
.PHONY : SearchAlgs/Heur.c.s

SearchAlgs/IDS.o: SearchAlgs/IDS.c.o
.PHONY : SearchAlgs/IDS.o

# target to build an object file
SearchAlgs/IDS.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/IDS.c.o
.PHONY : SearchAlgs/IDS.c.o

SearchAlgs/IDS.i: SearchAlgs/IDS.c.i
.PHONY : SearchAlgs/IDS.i

# target to preprocess a source file
SearchAlgs/IDS.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/IDS.c.i
.PHONY : SearchAlgs/IDS.c.i

SearchAlgs/IDS.s: SearchAlgs/IDS.c.s
.PHONY : SearchAlgs/IDS.s

# target to generate assembly for a file
SearchAlgs/IDS.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/IDS.c.s
.PHONY : SearchAlgs/IDS.c.s

SearchAlgs/Movimentos.o: SearchAlgs/Movimentos.c.o
.PHONY : SearchAlgs/Movimentos.o

# target to build an object file
SearchAlgs/Movimentos.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Movimentos.c.o
.PHONY : SearchAlgs/Movimentos.c.o

SearchAlgs/Movimentos.i: SearchAlgs/Movimentos.c.i
.PHONY : SearchAlgs/Movimentos.i

# target to preprocess a source file
SearchAlgs/Movimentos.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Movimentos.c.i
.PHONY : SearchAlgs/Movimentos.c.i

SearchAlgs/Movimentos.s: SearchAlgs/Movimentos.c.s
.PHONY : SearchAlgs/Movimentos.s

# target to generate assembly for a file
SearchAlgs/Movimentos.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/SearchAlgs/Movimentos.c.s
.PHONY : SearchAlgs/Movimentos.c.s

Utils/BoardUtils.o: Utils/BoardUtils.c.o
.PHONY : Utils/BoardUtils.o

# target to build an object file
Utils/BoardUtils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/Utils/BoardUtils.c.o
.PHONY : Utils/BoardUtils.c.o

Utils/BoardUtils.i: Utils/BoardUtils.c.i
.PHONY : Utils/BoardUtils.i

# target to preprocess a source file
Utils/BoardUtils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/Utils/BoardUtils.c.i
.PHONY : Utils/BoardUtils.c.i

Utils/BoardUtils.s: Utils/BoardUtils.c.s
.PHONY : Utils/BoardUtils.s

# target to generate assembly for a file
Utils/BoardUtils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/Utils/BoardUtils.c.s
.PHONY : Utils/BoardUtils.c.s

Utils/Timer.o: Utils/Timer.c.o
.PHONY : Utils/Timer.o

# target to build an object file
Utils/Timer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/Utils/Timer.c.o
.PHONY : Utils/Timer.c.o

Utils/Timer.i: Utils/Timer.c.i
.PHONY : Utils/Timer.i

# target to preprocess a source file
Utils/Timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/Utils/Timer.c.i
.PHONY : Utils/Timer.c.i

Utils/Timer.s: Utils/Timer.c.s
.PHONY : Utils/Timer.s

# target to generate assembly for a file
Utils/Timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/Utils/Timer.c.s
.PHONY : Utils/Timer.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IA.dir/build.make CMakeFiles/IA.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IA"
	@echo "... DataStructures/BFSBoard.o"
	@echo "... DataStructures/BFSBoard.i"
	@echo "... DataStructures/BFSBoard.s"
	@echo "... DataStructures/BoardList.o"
	@echo "... DataStructures/BoardList.i"
	@echo "... DataStructures/BoardList.s"
	@echo "... DataStructures/BoardStack.o"
	@echo "... DataStructures/BoardStack.i"
	@echo "... DataStructures/BoardStack.s"
	@echo "... DataStructures/DFSBoard.o"
	@echo "... DataStructures/DFSBoard.i"
	@echo "... DataStructures/DFSBoard.s"
	@echo "... DataStructures/DFSBoardStack.o"
	@echo "... DataStructures/DFSBoardStack.i"
	@echo "... DataStructures/DFSBoardStack.s"
	@echo "... DataStructures/HashStack.o"
	@echo "... DataStructures/HashStack.i"
	@echo "... DataStructures/HashStack.s"
	@echo "... DataStructures/Heap.o"
	@echo "... DataStructures/Heap.i"
	@echo "... DataStructures/Heap.s"
	@echo "... DataStructures/IDSBoard.o"
	@echo "... DataStructures/IDSBoard.i"
	@echo "... DataStructures/IDSBoard.s"
	@echo "... DataStructures/MovementStack.o"
	@echo "... DataStructures/MovementStack.i"
	@echo "... DataStructures/MovementStack.s"
	@echo "... DataStructures/Queue.o"
	@echo "... DataStructures/Queue.i"
	@echo "... DataStructures/Queue.s"
	@echo "... DataStructures/Stack.o"
	@echo "... DataStructures/Stack.i"
	@echo "... DataStructures/Stack.s"
	@echo "... SearchAlgs/A*.o"
	@echo "... SearchAlgs/A*.i"
	@echo "... SearchAlgs/A*.s"
	@echo "... SearchAlgs/BFS.o"
	@echo "... SearchAlgs/BFS.i"
	@echo "... SearchAlgs/BFS.s"
	@echo "... SearchAlgs/BP.o"
	@echo "... SearchAlgs/BP.i"
	@echo "... SearchAlgs/BP.s"
	@echo "... SearchAlgs/DFS.o"
	@echo "... SearchAlgs/DFS.i"
	@echo "... SearchAlgs/DFS.s"
	@echo "... SearchAlgs/Guloso.o"
	@echo "... SearchAlgs/Guloso.i"
	@echo "... SearchAlgs/Guloso.s"
	@echo "... SearchAlgs/Heur.o"
	@echo "... SearchAlgs/Heur.i"
	@echo "... SearchAlgs/Heur.s"
	@echo "... SearchAlgs/IDS.o"
	@echo "... SearchAlgs/IDS.i"
	@echo "... SearchAlgs/IDS.s"
	@echo "... SearchAlgs/Movimentos.o"
	@echo "... SearchAlgs/Movimentos.i"
	@echo "... SearchAlgs/Movimentos.s"
	@echo "... Utils/BoardUtils.o"
	@echo "... Utils/BoardUtils.i"
	@echo "... Utils/BoardUtils.s"
	@echo "... Utils/Timer.o"
	@echo "... Utils/Timer.i"
	@echo "... Utils/Timer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

